name: geolocation
description: Geolocation plugin for iOS and Android.
version: 0.2.1
author: Loup Inc. <hello@intheloup.io>
homepage: https://github.com/loup-v/geolocation

environment:
  sdk: '>=1.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  streams_channel:
    git: 
      url: git://github.com/osamagamal65/streams_channel.git
      ref: master

flutter:
  plugin:
    androidPackage: io.intheloup.geolocation
    pluginClass: GeolocationPlugin